version: "3"

x-deploy: &template-deploy
  replicas: 1
  restart_policy:
    condition: any
  update_config:
    parallelism: 1
    delay: 10s

services:
  postgresql:
    image: postgres:16.0
    volumes:
      - /data-volume/postgresql-data:/var/lib/postgresql/data:Z
      - ../postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ../envs/db_postgres.env
    networks:
      - "gitlab"
    ports:
      - "5432:5432"
    deploy:
      <<: *template-deploy
      labels:
        - "traefik.enable=false"

networks:
  gitlab:
    external: true
